// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvX8DjUybjB4sWS4tkcDhh-ISOF-hkMw8',
    appId: '1:83262093826:web:255862c2cff182e600451b',
    messagingSenderId: '83262093826',
    projectId: 'catatanpribadi-uts',
    authDomain: 'catatanpribadi-uts.firebaseapp.com',
    storageBucket: 'catatanpribadi-uts.firebasestorage.app',
    measurementId: 'G-LH24R9EEWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Ot9SEH22r11bf7IPewFNcIVzDLpJ8xk',
    appId: '1:83262093826:android:95829da363f53ad700451b',
    messagingSenderId: '83262093826',
    projectId: 'catatanpribadi-uts',
    storageBucket: 'catatanpribadi-uts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdExHwWFRtKrmKDKma9OYezEuAg5jwgEI',
    appId: '1:83262093826:ios:c8e3ea9ee49cc88300451b',
    messagingSenderId: '83262093826',
    projectId: 'catatanpribadi-uts',
    storageBucket: 'catatanpribadi-uts.firebasestorage.app',
    iosBundleId: 'com.example.catatanpribadiUts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdExHwWFRtKrmKDKma9OYezEuAg5jwgEI',
    appId: '1:83262093826:ios:c8e3ea9ee49cc88300451b',
    messagingSenderId: '83262093826',
    projectId: 'catatanpribadi-uts',
    storageBucket: 'catatanpribadi-uts.firebasestorage.app',
    iosBundleId: 'com.example.catatanpribadiUts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvX8DjUybjB4sWS4tkcDhh-ISOF-hkMw8',
    appId: '1:83262093826:web:e65d0a412f873c0100451b',
    messagingSenderId: '83262093826',
    projectId: 'catatanpribadi-uts',
    authDomain: 'catatanpribadi-uts.firebaseapp.com',
    storageBucket: 'catatanpribadi-uts.firebasestorage.app',
    measurementId: 'G-WXV305T9SF',
  );
}
